### ISSUE TITLE
--disabled-gpu vs --disable-gpu

### ISSUE THREAD

**Issue by sieben07** [rastasheep/alpine-node-chromium#3]
https://developers.google.com/web/updates/2017/04/headless-chrome

I think it should be --diable-gpu

browsers: ['ChromiumNoSandbox'],
  customLaunchers: {
    ChromiumNoSandbox: {
      base: 'ChromiumHeadless',
      flags: ['--no-sandbox', '--headless', '--disabled-gpu']
    }
  }

**Comment by rastasheep** [comment]
Thanks @sieben07 i've updated readme.
